"""
Django settings for wepol project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""


print("Development Mode")
from .base import *

DEBUG = True
KEY_BILL_INFO = 'hr45jWpc1dmMidXc5P3972DknBUxYAWElTbxlskPrRNqDD3ej5r6CW7ucKGAAI2LyH39Hkum3bE0A8HQQ9lAGQ%3D%3D'
KEY_LAW_INFO = 'hr45jWpc1dmMidXc5P3972DknBUxYAWElTbxlskPrRNqDD3ej5r6CW7ucKGAAI2LyH39Hkum3bE0A8HQQ9lAGQ%3D%3D'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wepol',
        'USER': 'root',
        'PASSWORD': '1234',
        'HOST': '127.0.0.1',
        'PORT': 3306,
    }
}
