# Generated by Django 3.2.6 on 2021-08-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRuleModel',
            fields=[
                ('admin_rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_rule_identification', models.CharField(max_length=20)),
                ('admin_rule_serial', models.CharField(max_length=20)),
                ('admin_rule_name', models.CharField(max_length=200)),
                ('admin_rule_type', models.CharField(max_length=10)),
                ('issue_date', models.CharField(max_length=20)),
                ('issue_number', models.CharField(max_length=20)),
                ('competent_department_name', models.CharField(max_length=50)),
                ('history_class', models.CharField(max_length=20)),
                ('revision_class_code', models.CharField(max_length=10)),
                ('revision_class_name', models.CharField(max_length=20)),
                ('admin_rule_detail_link', models.CharField(max_length=500)),
                ('effective_date', models.CharField(max_length=20)),
                ('creation_date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'admin_rules',
            },
        ),
        migrations.CreateModel(
            name='DetcModel',
            fields=[
                ('detc_id', models.AutoField(primary_key=True, serialize=False)),
                ('detc_serial', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=20)),
                ('case_number', models.CharField(max_length=20)),
                ('case_name', models.CharField(max_length=500)),
                ('detc_detail_link', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'detc',
            },
        ),
        migrations.CreateModel(
            name='ExpcModel',
            fields=[
                ('expc_id', models.AutoField(primary_key=True, serialize=False)),
                ('expc_serial', models.CharField(max_length=10)),
                ('agenda_name', models.CharField(max_length=500)),
                ('agenda_number', models.CharField(max_length=20)),
                ('inquiry_org_name', models.CharField(max_length=20)),
                ('inquiry_org_code', models.CharField(max_length=10)),
                ('reply_org_name', models.CharField(max_length=20)),
                ('reply_org_code', models.CharField(max_length=10)),
                ('reply_date', models.CharField(max_length=20)),
                ('expc_class_name', models.CharField(max_length=20, null=True)),
                ('expc_detail_link', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'expcs',
            },
        ),
        migrations.CreateModel(
            name='LawModel',
            fields=[
                ('law_id', models.AutoField(primary_key=True, serialize=False)),
                ('law_identification', models.CharField(max_length=20)),
                ('law_serial', models.CharField(max_length=20)),
                ('current_history_code', models.CharField(max_length=20)),
                ('law_korean_name', models.CharField(max_length=200)),
                ('law_short_name', models.CharField(max_length=200)),
                ('announcement_date', models.CharField(max_length=20)),
                ('announcement_number', models.CharField(max_length=20)),
                ('revision_class_name', models.CharField(max_length=20)),
                ('competent_department_code', models.CharField(max_length=20)),
                ('competent_department_name', models.CharField(max_length=20)),
                ('law_class_name', models.CharField(max_length=20)),
                ('effective_date', models.CharField(max_length=20)),
                ('is_other_law', models.CharField(max_length=20, null=True)),
                ('law_detail_link', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'laws',
            },
        ),
        migrations.CreateModel(
            name='LicbylModel',
            fields=[
                ('licbyl_id', models.AutoField(primary_key=True, serialize=False)),
                ('licbyl_serial', models.CharField(max_length=10)),
                ('related_law_serial', models.CharField(max_length=10)),
                ('related_law_id', models.CharField(max_length=10)),
                ('licbyl_name', models.CharField(max_length=500)),
                ('related_law_name', models.CharField(max_length=500)),
                ('licbyl_number', models.CharField(max_length=10)),
                ('licbyl_type', models.CharField(max_length=20)),
                ('competent_department_name', models.CharField(max_length=50)),
                ('announcement_date', models.CharField(max_length=10)),
                ('announcement_number', models.CharField(max_length=10)),
                ('revision_class_name', models.CharField(max_length=20)),
                ('law_type', models.CharField(max_length=20)),
                ('licbyl_format_file_link', models.CharField(max_length=200)),
                ('licbyl_format_pdf_link', models.CharField(max_length=200)),
                ('licbyl_law_detail_link', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'licbyls',
            },
        ),
        migrations.CreateModel(
            name='LstrmModel',
            fields=[
                ('lstrm_id', models.AutoField(primary_key=True, serialize=False)),
                ('lstrm_identification', models.CharField(max_length=10)),
                ('lstrm_name', models.CharField(max_length=200)),
                ('lstrm_detail_search', models.CharField(max_length=500)),
                ('lstrm_detail_link', models.CharField(max_length=500)),
                ('dict_class_code', models.CharField(max_length=10)),
                ('law_type_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'lstrms',
            },
        ),
        migrations.CreateModel(
            name='OrdinModel',
            fields=[
                ('ordin_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordin_identification', models.CharField(max_length=20)),
                ('ordin_serial', models.CharField(max_length=20)),
                ('ordin_name', models.CharField(max_length=500)),
                ('announcement_date', models.CharField(max_length=20)),
                ('announcement_number', models.CharField(max_length=10)),
                ('revision_class_name', models.CharField(max_length=10)),
                ('local_gov_agency_name', models.CharField(max_length=20)),
                ('ordin_type', models.CharField(max_length=10)),
                ('effective_date', models.CharField(max_length=20)),
                ('ordin_detail_link', models.CharField(max_length=500)),
                ('ordin_field_name', models.CharField(max_length=10, null=True)),
                ('reference_data_class', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'ordins',
            },
        ),
        migrations.CreateModel(
            name='TrtyModel',
            fields=[
                ('trty_id', models.AutoField(primary_key=True, serialize=False)),
                ('trty_serial', models.CharField(max_length=10)),
                ('trty_name', models.CharField(max_length=500)),
                ('trty_class_code', models.CharField(max_length=10)),
                ('trty_class_name', models.CharField(max_length=20)),
                ('effective_date', models.CharField(max_length=20)),
                ('signature_date', models.CharField(max_length=20, null=True)),
                ('gazette_publication_date', models.CharField(max_length=20)),
                ('trty_number', models.CharField(max_length=20)),
                ('country_number', models.CharField(max_length=10, null=True)),
                ('trty_detail_link', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'trtys',
            },
        ),
    ]
